data_ingestion:
  root_dir: data
  source_URL: https://drive.google.com/file/d/1cfq70IG4wxvAVPLqGi7RXZPNxZ4LMMhb/view?usp=sharing
  local_data_file: data/brain_mri.zip
  unzip_dir: data

artifacts_root: artifacts

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: data/BRAIN MRI
  img_size: 128

model_training:
  root_dir: artifacts/model_training
  train_data_path: artifacts/data_transformation/X_train.npy

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation
  model_path: trainedmodels
